# update-docs-tree.ps1 -- Generate project docs trees and workspace taxonomy inventory.
# Usage:
#   update-docs-tree.ps1 -Mode write
#   update-docs-tree.ps1 -Mode check

param(
    [ValidateSet("write", "check")]
    [string]$Mode = "write"
)

$ErrorActionPreference = "Stop"

$WorkspaceRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ProjectRoot = Join-Path $WorkspaceRoot "Project"
$DocsAiRoot = Join-Path $WorkspaceRoot "Docs\AI"
$InventoryPath = Join-Path $DocsAiRoot "document-taxonomy-inventory.md"
$Today = Get-Date -Format "yyyy-MM-dd"

$DocRoots = @(
    "00-Overview",
    "01-Planning",
    "02-Design",
    "03-Architecture",
    "04-Implementation",
    "05-Testing",
    "06-Operations",
    "07-Decisions",
    "99-Archive"
)

function Write-Red { Write-Host $args[0] -ForegroundColor Red }
function Write-Green { Write-Host $args[0] -ForegroundColor Green }
function Write-Yellow { Write-Host $args[0] -ForegroundColor Yellow }

function Convert-ToSlash {
    param([string]$Path)
    return ($Path -replace "\\", "/")
}

function Get-RelativePath {
    param([string]$Base, [string]$Path)
    $baseFull = [System.IO.Path]::GetFullPath($Base).TrimEnd('\') + '\'
    $pathFull = [System.IO.Path]::GetFullPath($Path)
    if ($pathFull.StartsWith($baseFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        return Convert-ToSlash ($pathFull.Substring($baseFull.Length))
    }
    return Convert-ToSlash $pathFull
}

function Test-IsClassifiedDoc {
    param([string]$RelativePath)
    if ($RelativePath -eq "DOCS_TREE.md") { return $true }
    $first = ($RelativePath -split "/")[0]
    return ($first -in $DocRoots)
}

function Test-IsRedirectStub {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return $false }
    $head = Get-Content -LiteralPath $Path -TotalCount 5 -ErrorAction SilentlyContinue
    return (($head -join "`n") -match "doc-migration-redirect")
}

function Get-SuggestedTarget {
    param([string]$RelativePath)
    $lower = $RelativePath.ToLowerInvariant()
    $name = Split-Path $RelativePath -Leaf

    if ($lower -match "archive|deprecated|old") { return "99-Archive/Legacy/$name" }
    if ($lower -match "test|qa|review|verify|verification|result|report|fix") { return "05-Testing/General/$name" }
    if ($lower -match "plan|roadmap|target|progress") { return "01-Planning/General/$name" }
    if ($lower -match "design|spec|schema|gameplay|system") { return "02-Design/General/$name" }
    if ($lower -match "architecture|api|reference|mcp|module|integration") { return "03-Architecture/General/$name" }
    if ($lower -match "script|build|deploy|encoding|operation|runbook") { return "06-Operations/General/$name" }
    if ($lower -match "decision|adr") { return "07-Decisions/General/$name" }
    if ($lower -match "readme|overview|guide|tutorial") { return "00-Overview/General/$name" }
    return "00-Overview/General/$name"
}

function New-ProjectDocsTree {
    param([System.IO.DirectoryInfo]$Project)

    $docsDir = Join-Path $Project.FullName "Docs"
    $treePath = Join-Path $docsDir "DOCS_TREE.md"

    if ($Mode -eq "check") {
        if (-not (Test-Path $docsDir)) { throw "Docs directory missing: $docsDir" }
        if (-not (Test-Path $treePath)) { throw "DOCS_TREE.md missing: $treePath" }
        return [pscustomobject]@{
            Project = $Project.Name
            DocsCount = 0
            LegacyCount = 0
            Tree = $treePath
        }
    }

    New-Item -ItemType Directory -Path $docsDir -Force | Out-Null
    foreach ($root in $DocRoots) {
        New-Item -ItemType Directory -Path (Join-Path $docsDir $root) -Force | Out-Null
    }

    $markdownDocs = @(Get-ChildItem -LiteralPath $docsDir -Recurse -File -Filter "*.md" -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -ne $treePath } |
        Sort-Object FullName)

    $classified = @()
    $legacy = @()
    $redirects = @()
    foreach ($doc in $markdownDocs) {
        $rel = Get-RelativePath $docsDir $doc.FullName
        $row = [pscustomobject]@{
            Path = $rel
            Suggested = Get-SuggestedTarget $rel
        }
        if (Test-IsRedirectStub $doc.FullName) { $redirects += $row }
        elseif (Test-IsClassifiedDoc $rel) { $classified += $row }
        else { $legacy += $row }
    }

    $lines = @(
        "# $($Project.Name) Docs Tree",
        "",
        "Last updated: $Today",
        "Generated by: .trae/scripts/update-docs-tree.ps1",
        "",
        "## Purpose",
        "",
        "This file is the document map for Project/$($Project.Name). Project code changes must update same-project docs and this tree.",
        "",
        "## Canonical Directory Rules",
        "",
        "| Directory | Purpose |",
        "|---|---|",
        "| 00-Overview/ | Project overview, entrypoints, glossary |",
        "| 01-Planning/<System>/ | Product planning, feature planning, roadmap notes |",
        "| 02-Design/<System>/ | Gameplay, product, UX, content, and system design specs |",
        "| 03-Architecture/<System>/ | Architecture, module boundaries, data flow, integration contracts |",
        "| 04-Implementation/<System>/ | Implementation notes, code-to-doc mapping, change records |",
        "| 05-Testing/<System>/ | Test plans, QA notes, verification reports |",
        "| 06-Operations/<System>/ | Build, release, deployment, runbooks |",
        "| 07-Decisions/<System>/ | ADRs and durable decisions |",
        "| 99-Archive/ | Historical or superseded material |",
        "",
        "## Classified Docs",
        "",
        "| Path |",
        "|---|"
    )

    if ($classified.Count -eq 0) { $lines += "| _None yet_ |" }
    else {
        foreach ($row in $classified) { $lines += "| $($row.Path) |" }
    }

    $lines += @(
        "",
        "## Legacy / Unclassified Docs",
        "",
        "These files remain in place during the first pass. Move them only after checking references.",
        "",
        "| Current Path | Suggested Target |",
        "|---|---|"
    )

    if ($legacy.Count -eq 0) { $lines += "| _None_ | _None_ |" }
    else {
        foreach ($row in $legacy) { $lines += "| $($row.Path) | $($row.Suggested) |" }
    }

    $lines += @(
        "",
        "## Redirect Stubs",
        "",
        "These files preserve old inbound links after migration.",
        "",
        "| Old Path |",
        "|---|"
    )

    if ($redirects.Count -eq 0) { $lines += "| _None_ |" }
    else {
        foreach ($row in $redirects) { $lines += "| $($row.Path) |" }
    }

    $lines += @(
        "",
        "## Recent Updates",
        "",
        "| Date | Task | Code Scope | Docs Updated |",
        "|---|---|---|---|",
        "| $Today | docs-taxonomy-refresh | Project docs tree generation | Docs/DOCS_TREE.md |"
    )

    [System.IO.File]::WriteAllLines($treePath, $lines, [System.Text.UTF8Encoding]::new($false))

    return [pscustomobject]@{
        Project = $Project.Name
        DocsCount = $markdownDocs.Count
        LegacyCount = $legacy.Count
        RedirectCount = $redirects.Count
        Tree = $treePath
    }
}

function New-WorkspaceInventory {
    param([object[]]$ProjectRows)

    if ($Mode -eq "check") {
        if (-not (Test-Path $InventoryPath)) { throw "Inventory missing: $InventoryPath" }
        foreach ($required in @(
            "27-AI-Workflow-Refactor-Manifest.md",
            "28-Documentation-Governance-Workflow.md",
            "README.md",
            ".cache-manifest.md"
        )) {
            $path = Join-Path $DocsAiRoot $required
            if (-not (Test-Path $path)) { throw "Required Docs/AI file missing: $path" }
        }
        return
    }

    $rootDocs = @(Get-ChildItem -LiteralPath (Join-Path $WorkspaceRoot "Docs") -Directory -ErrorAction SilentlyContinue | Sort-Object Name)
    $rootRows = @()
    foreach ($dir in $rootDocs) {
        $role = switch -Regex ($dir.Name) {
            "^AI$" { "global-ai-workflow"; break }
            "^superpowers$" { "canonical-specs-and-plans"; break }
            "^_shared$" { "optional-mirror-or-history"; break }
            "^Memory$" { "failure-memory"; break }
            "^(airpgweb|characterdesigntool|rts)$" {
                # Classify based on actual content
                $mdFiles = @(Get-ChildItem -LiteralPath $dir.FullName -Filter "*.md" -File -Recurse -ErrorAction SilentlyContinue)
                $nonStub = @($mdFiles | Where-Object {
                    $content = Get-Content -LiteralPath $_.FullName -Raw -ErrorAction SilentlyContinue
                    $content -notmatch '<!-- doc-migration-redirect -->'
                })
                if ($nonStub.Count -gt 0) { "legacy-project-mirror-candidate" }
                elseif ($mdFiles.Count -gt 0) { "legacy-project-mirror-redirects" }
                else { "legacy-project-mirror-empty" }
                break
            }
            default { "global-reference" }
        }
        $rootRows += [pscustomobject]@{ Name = $dir.Name; Role = $role }
    }

    $lines = @(
        "# Document Taxonomy Inventory",
        "",
        "Date: $Today",
        "Generated by: .trae/scripts/update-docs-tree.ps1",
        "Mode: non-destructive first pass",
        "",
        "## Canonical Rules",
        "",
        "| Class | Canonical Location |",
        "|---|---|",
        "| Global AI workflow docs | Docs/AI/NN-*.md |",
        "| Formal design specs | Docs/superpowers/specs/YYYY-MM-DD-*-design.md |",
        "| Implementation plans | Docs/superpowers/plans/YYYY-MM-DD-*-plan.md |",
        "| Runtime task docs | .trae/tasks/<scope>/<task>/ and .opencode/tasks/<scope>/<task>/ |",
        "| Project docs | Project/<ProjectName>/Docs/ |",
        "| Memory docs | Docs/Memory/ |",
        "",
        "## Root Docs Directories",
        "",
        "| Directory | Classification |",
        "|---|---|"
    )

    foreach ($row in $rootRows) {
        $lines += "| Docs/$($row.Name)/ | $($row.Role) |"
    }

    $lines += @(
        "",
        "## Project Docs Status",
        "",
        "| Project | Markdown Docs | Legacy / Unclassified | Redirect Stubs | Docs Tree |",
        "|---|---:|---:|---:|---|"
    )

    foreach ($row in ($ProjectRows | Sort-Object Project)) {
        $treeRel = Get-RelativePath $WorkspaceRoot $row.Tree
        $lines += "| $($row.Project) | $($row.DocsCount) | $($row.LegacyCount) | $($row.RedirectCount) | $treeRel |"
    }

    $lines += @(
        "",
        "## Migration Notes",
        "",
        "- Project/<ProjectName>/Docs/DOCS_TREE.md now lists classified docs, legacy docs, and redirect stubs for each project.",
        "- Project-internal docs can be migrated with .trae/scripts/migrate-docs.ps1.",
        "- Redirect stubs preserve old inbound links after migration.",
        "- Move remaining legacy docs only after checking inbound links with rg.",
        "- Root Docs/airpgweb/, Docs/characterdesigntool/, and Docs/rts/ are classified by content: redirects-only, empty, or candidate.",
        "- Root Docs/AI/, Docs/superpowers/, and Docs/Memory/ remain canonical global locations."
    )

    [System.IO.File]::WriteAllLines($InventoryPath, $lines, [System.Text.UTF8Encoding]::new($false))
}

try {
    $projects = @(Get-ChildItem -LiteralPath $ProjectRoot -Directory -ErrorAction Stop | Sort-Object Name)
    $rows = @()
    foreach ($project in $projects) {
        $rows += New-ProjectDocsTree -Project $project
    }
    New-WorkspaceInventory -ProjectRows $rows

    if ($Mode -eq "check") {
        Write-Green "[docs-tree] check passed"
    }
    else {
        Write-Green "[docs-tree] updated $($rows.Count) project trees and workspace inventory"
    }
    exit 0
}
catch {
    Write-Red "[docs-tree] $($_.Exception.Message)"
    exit 1
}
